columnSuffix: zcppsliq
contentColumnType: text
fieldGroup: 6f30c6f3-1016-486f-bcfb-669d01377c1f # Listings
handle: postalCode
instructions: null
name: 'Postal Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
